### ISSUE TITLE
delay(10) and voltage inccorrect

### ISSUE THREAD

**Issue by mateusz-kusmierz** [MacroYau/LTC2942-Arduino-Library#2]
Hello, i have found 2 issues.
You use delay in your library - that is not the great idea. 10ms of delay is killing my main software.
You should use millis or some other timing.
Voltage is not correct. I don't know why. Real voltage (measured by many meters, measured on ltc2942 pin) is 4.052V, but when pulling out voltage in software it is about 4.130V. This is huge difference. This problem is not related to hardware or soldering since I checked it on 10 boards and it is the same.
EDIT: Voltage is higher about 0.078V - that is 78mV and that is resolution of ltc2942 :(

**Comment by MacroYau** [comment]
Hi, the `delay(10)` was introduced as the library [defaults](https://github.com/MacroYau/LTC2942-Arduino-Library/blob/ca321551a358d3675bbe72e95da1aa9add940f78/src/LTC2942.cpp#L65) to the one-shot ADC mode. You can refer to the device datasheet and the library source code to adopt an alternative implementation that suits best for your use case.

I have no concrete idea on the voltage accuracy. If I were you, I would try to set the ADC mode to continuous (rather than one-shot) to see if the device can settle to a more accurate reading.

**Comment by MacroYau** [comment]
Closed due to inactivity.
